export enum AccountInfoExtra {
  PrivateBoosters = 'private.boosters',
  PrivateGarage = 'private.garage',
  PrivateGroupedContacts = 'private.grouped_contacts',
  PrivatePersonalMissions = 'private.personal_missions',
  PrivateRented = 'private.rented',
  StatisticsEpic = 'statistics.epic',
  StatisticsFallout = 'statistics.fallout',
  StatisticsGlobalMapAbsolute = 'statistics.globalmap_absolute',
  StatisticsGlobalMapChampion = 'statistics.globalmap_champion',
  StatisticsMapMiddle = 'statistics.globalmap_middle',
  StatisticsRandom = 'statistics.random',
  StatisticsRanked10x10 = 'statistics.ranked_10x10',
  StatisticsRanked15x15 = 'statistics.ranked_15x15',
  StatisticsRankedBattles = 'statistics.ranked_battles',
  StatisticsRankedBattlesCurrent = 'statistics.ranked_battles_current',
  StatisticsRankedBattlesPrevious = 'statistics.ranked_battles_previous',
  StatisticsRankedSeasons1 = 'statistics.ranked_season_1',
  StatisticsRankedSeasons2 = 'statistics.ranked_season_2',
  StatisticsRankedSeasons3 = 'statistics.ranked_season_3',
}
